### ISSUE TITLE
Update to newer version

### ISSUE THREAD

**Issue by stkolome** [EVOLVED-5G/SDK-CLI#19]
I would like to bump the tool to a newer version with all the latest updates. I feel the tool is mature enough now to bump it to v0.5.0 (or even more, let me know if you agree or not) and push to PIP. What I need from you, is to update the HISTORY file. Please enter you latest updates in the file in order to keep a record. Thanks

**Comment by AlexJoom** [comment]
I need a lil help here

At the history file the latest addition is 

**0.1.9 (2021-20-09)**

@skolome  i assume that you will add the 0.5.0 right? And that you propose to skip 0.2.5 (i agree)

I'm sending Maggioli's history for this latest version

* Added class LocationSubscriber to SDK. A class that allows to get location monitoring reports from the 5G-API

**Comment by rimarala** [comment]
It can be closed, it is an old comment. Everything has been updated.
