### ISSUE TITLE
User to have the option to choose branch other than the default during pipeline execution

### ISSUE THREAD

**Issue by stkolome** [EVOLVED-5G/SDK-CLI#26]
I think it would be good if the users had the option to choose the branch they would like to deploy with the various pipelines execution. I think now the default is "evolved5g" (which exists in every new NetApp), but it would be nice to be able to choose another branch.

**Comment by rimarala** [comment]
For the moment let's leave it as it is, evolved5g branch should be the one with the latest changes/updates to test in the CI/CD, so everyone is aligned.
